name: Rescrape Auctions Workflow

on:
    workflow_dispatch:
        inputs:
            rescrape_obj_key:
                description: "S3 object key for rescrape URLs file (.txt)"
                required: true
            TaskToken:
                description: "Step Function task token"
                required: true

jobs:
    rescrape:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: "Setup Python"
              uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"

            - name: Install the project
              run: uv sync --locked --all-extras --dev
            
            - name: Save urls to /tmp/rescrape/urls.txt
              run: |
                mkdir -p /tmp/rescrape
                echo "${{ github.event.inputs.rescrape_obj_key }}" > /tmp/rescrape/rescrape_object.txt
                echo "${{ github.event.inputs.TaskToken }}" > /tmp/rescrape/task_token.txt

            - name: Run Rescrape
              run: uv run src/rescrape/main.py
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
                PROCESSED_AUCTIONS_BUCKET: ${{ secrets.PROCESSED_AUCTIONS_BUCKET }}
                RAW_AUCTIONS_BUCKET: ${{ secrets.RAW_AUCTIONS_BUCKET }}
                RESCRAPE_BUCKET_DIR: ${{ secrets.RESCRAPE_BUCKET_DIR }}
                URLS_BUCKET: ${{ secrets.URLS_BUCKET }}
          